### PR TITLE
Milestone 6: Final version of CashSync App

### PR DESCRIPTION
**Pull request by Xghayor**
In this milestone i implemented:

1. Use ruby gems as software packages system.
2. Install Ruby on Rails framework.
3. Understand Rails RESTful design and router.
4. Use controllers to handle requests and render empty views.
5. Use params from browser request in a safe way.
6. Use preprocessed html file with embedded Ruby code.
7. Use layouts and templates for shared content.
8. Use database migration files to maintain database schema.
9. Use validations for models.
10. Secure app from n+1 problems.
11. Understand what ORM is.
12. Write SQL queries with ActiveRecord.
13. Set up associations between models.
14. Build a webapp that requires the user to log in.
15. Use devise gem for authentication.
16. Limit access to webapp resources based on authorization rules.
17. Analyze in writing why you have made a coding choice using one structure over another.

here is the link to video description: 
https://www.loom.com/share/c8ad6f875eac498f875a866d88182525?sid=163fac68-7fce-46b2-ad20-ee92aacc0276

### CODE REVIEW

**Review by franclobo — CHANGES_REQUESTED** [review]
Hi @Xghayor, 

# Suggested changes ♻️ 

so-close-jim-halpert

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Git flow ✔️ 
- All tests passed ✔️ 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- It is not possible to use inline comments due to there isn't the corresponding CSS file.
- [ ] Kindly correct the with in the transaction window to avoid scroll-X, it could be better to use width: 100%, it is just a suggestion for a better UX.

```css
.container {
  width: 100%;
}
```


https://github.com/Xghayor/cashsync-app/assets/58642949/f7f72b75-f52d-4b8c-9890-7e0e423b9983

- [x] Kindly add in your video a highlight about a piece of the code that you find interesting or are proud of making for professional documentation.

image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Xghayor** [comment]
Hi @franclobo 

Thanks for the review.

at 0.58 sec, i have mentioned a part where i'm proud of making it.
as per the instruction we should show a piece of code or something i built.
please check , Thanks

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Xghayor👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- Good job with model validations. ✔️ 
- Nice UI design. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️



 ## Required Changes ♻️

- [ ] As requested by the previous reviewer, Please make sure in the presentation video you highlight some interesting piece of code that you are very proud of. (You highlighted the functionality on the UI but showing the code will make you more comfortable talking about code with people, You should re record the video and highlight some interesting piece of code)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Xghayor** [comment]
@thecodechaser 

Thanks for the review.

I have updated the video link with the completed video requirement.

**Review by Abenezer-Tilahun — APPROVED** [review]
Hi @Xghayor 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes. 
✔️ Good job for Implemented RoR capstone project - day 3.


## Optional suggestions 


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

**Pull request merged**
